### ISSUE TITLE
iPhone version.

### ISSUE THREAD

**Issue by merzaff** [servy/dnd5spellbook#6]
Could you create iPhone version , please?

**Comment by servy** [comment]
If you provided me with an iPhone to develop and test it, I would definitely consider the development. As of now, I have no plans to bother developing iPhone apps in the nearest future.

But you can write it yourself! If you choose to develop an iPhone version you can make use of extracted data from [spell_metadata.xml](https://github.com/servy/dnd5spellbook/blob/master/app/src/main/assets/dndbundle/spell_metadata.xml) and html spell files in the [assets](https://github.com/servy/dnd5spellbook/blob/master/app/src/main/assets/dndbundle/) as [dnd5spellbookweb](https://github.com/Otanikotani/dnd5spellbookweb) project did.

Also, you could try to modify this [web fork](https://github.com/Otanikotani/dnd5spellbookweb) of dnd5spellbook to run on your iPhone with no internet connection needed using something like [phonegap](http://phonegap.com/).
